version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    networks:
      - ecommerce

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    networks:
      - ecommerce

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    networks:
      - ecommerce

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge
